### PR TITLE
Bundle for localization files 

### PR DESCRIPTION
**Pull request by leobarrospereira**
Added localization files inside a bundle to not interfere with apps localization when DBCamera is used via cocoa pods.

### CODE REVIEW

**Comment by leobarrospereira** [comment]
With the localization files outside a bundle all localizations used on DBCamera are considered as languages of the main app when it's publish on App Store.

**Comment by danielebogo** [comment]
Hi @leobarrospereira , can you fix the conflict? I think the problem is because there's a new language added before. Maybe the german translation.

**Comment by leobarrospereira** [comment]
Hi @danielebogo , i will fix and push a new commit.

**Comment by danielebogo** [comment]
@leobarrospereira thanks man!

**Comment by leobarrospereira** [comment]
@danielebogo i fixed the conflict and added the new german language inside the localization bundle. Take a look.

**Comment by danielebogo** [comment]
Great! Thanks a lot!

**Comment by leobarrospereira** [comment]
:+1:

**Comment by mkoppanen** [comment]
It looks like that this change breaks usage with cocoapods use_frameworks! I just took a pull and getting following exception:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument'

**Comment by leobarrospereira** [comment]
Hi @mkoppanen i will change `mainBundle` and make another pull request.

**Comment by mkoppanen** [comment]
Cool, the following should work:

```
#ifndef DBCameraLocalizedStrings
#define DBCameraLocalizedStrings(key) \
[[NSBundle bundleWithPath:[[NSBundle bundleForClass:self.class] pathForResource:@"DBCamera" ofType:@"bundle"]] localizedStringForKey:(key) value:@"" table:@"DBCamera"]
#endif
```

**Comment by leobarrospereira** [comment]
Yeah, it's the point.

**Comment by leobarrospereira** [comment]
Pull request to fix this:
https://github.com/danielebogo/DBCamera/pull/178

**Pull request merged**
